import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "@/app/_block/link";
import { ReactNode } from "react";
import styles from "@/app/page.module.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav
          style={{
            display: "flex",
            columnGap: "6px",
            width: "100%",
            justifyContent: "center",
            paddingBlock: "8px",
            position: "fixed",
            top: 0,
            left: 0,
            background: "#151515",
          }}
        >
          <Link href={"/"}>Index</Link>
          <Link href={"/csr"}>CSR</Link>
          <Link href={"/ssr"}>SSR</Link>
          <Link href={"/ssg"}>SSG</Link>
          <Link href={"/isr"}>ISR</Link>
          <Link href={"/stream-render"}>Stream Render</Link>
          <Link href={"/edge-middleware"}>Middleware</Link>
          <Link href={"/server-action"}>Server Action</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
